### ISSUE TITLE
Undefined name 'part_seg' in lib/datasets/ade.py

### ISSUE THREAD

**Issue by cclauss** [endernewton/iter-reason#2]
$ __python2 -m flake8 . --count --select=E9,F82 --show-source --statistics__
```
./lib/datasets/ade.py:223:19: F821 undefined name 'part_seg'
            seg = part_seg
                  ^
1     F821 undefined name 'part_seg'
```

**Comment by endernewton** [comment]
where did you need this? I can clean this up actually.

**Comment by xueyoo** [comment]
does train_memory step need segmentation data?

**Comment by cclauss** [comment]
The line is probably not run currently because if it was __NameError__ would probably be raised at runtime.

**Comment by endernewton** [comment]
@xueyoo the segmentation is converted to boxes.

**Comment by endernewton** [comment]
@cclauss i removed that, thanks!
