### ISSUE TITLE
Have you modify it into pytorch？

### ISSUE THREAD

**Issue by destinyzs** [endernewton/iter-reason#3]
Have you modify it into pytorch？I think pytorch is better to use.

**Comment by endernewton** [comment]
yeah.. maybe in some time i will migrate it to pytorch. in the mean time you can also try yourself. :)

**Comment by destinyzs** [comment]
Yeah..try my best

**Comment by coderSkyChen** [comment]
@destinyzs Hi! I've reimplemented it on pytorch. Maybe it's useful for you.
https://github.com/coderSkyChen/Iterative-Visual-Reasoning.pytorch

**Comment by destinyzs** [comment]
oh, thanks a lot!
