### ISSUE TITLE
some questions about vgd

### ISSUE THREAD

**Issue by destinyzs** [endernewton/iter-reason#5]
what is the file `synsets.txt` in floder `/lib/datasets/visual_genome` #24?
I can not find this file in this project or at the vgd website `http://visualgenome.org/api/v0/api_home.html`..

**Comment by destinyzs** [comment]
@endernewton

**Comment by destinyzs** [comment]
Ok, got it!

**Comment by destinyzs** [comment]
oh……i still confuse,can you give me a favor?

**Comment by Kaze89** [comment]
Hi, @destinyzs , have you known where to get `synsets.txt`? I want to test vgd. Much appreciated!
